In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,0]},index=['a','b','c','d','e'])
df

   x  y
a  1  6
b  2  7
c  3  8
d  4  9
e  5  0

In [8]:
df[['x']]

   x
a  1
b  2
c  3
d  4
e  5

In [9]:
df[['a']]

KeyError: "None of [Index(['a'], dtype='object')] are in the [columns]"

In [15]:
df[[0]]

KeyError: "None of [Index([0], dtype='int32')] are in the [columns]"

In [11]:
s = pd.Series({'x':[1,2,3,4,5]})
s

x    [1, 2, 3, 4, 5]
dtype: object

In [12]:
s["x"]

[1, 2, 3, 4, 5]

In [13]:
s[0]

[1, 2, 3, 4, 5]

In [16]:
s[0][2]

3

In [22]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]

In [23]:
arr[0]

1

In [24]:
arr[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [25]:
arr[[0,1]]

array([1, 2])

In [26]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr2[0]

array([1, 2, 3, 4])

In [28]:
arr2[[0,1]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
arr2[1][[1,2]]

array([6, 7])

In [32]:
arr2[[0,1]][[2,3]] # We can't extract random multiple items of 2D array by indexing

IndexError: index 2 is out of bounds for axis 0 with size 2

In [33]:
arr2[[0,2],[1,3]]   # We can't extract random multiple items of 2D array by indexing

IndexError: index 2 is out of bounds for axis 0 with size 2

In [36]:
arr2[][0]   # we can't access columns values using indexing in numpy 2D array.

SyntaxError: invalid syntax (1896120328.py, line 1)

In [37]:
np.ones(4)

array([1., 1., 1., 1.])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [46]:
np.diag((3,2,))

array([[3, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [47]:
np.diag((3,4,2,5))

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 5]])